apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: customer-applications
spec:
  generators:
    - git:
        repoURL: https://github.com/rafimojabi/onetime-argo.git
        revision: HEAD
        files:
          - path: "generator.yaml"
  template:
    metadata:
      name: '{{customer.name}}'
    spec:
      project: default
      source:
        repoURL:  https://grafana.github.io/helm-charts
        targetRevision: 8.0.2
        chart: grafana
      destination:
        # Specify the server for each region
        name: '{{customer.region}}'
        namespace: '{{customer.name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
