apiVersion: v1
kind: Secret
metadata:
  name: avp-secret
  namespace: default
  annotations:
    avp.kubernetes.io/secret-version: "4"
    avp.kubernetes.io/path: "development/data/rafi-secret"
type: Opaque
stringData:
  secret-value: <>rafi-secret