apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-postgre-sql-connector2
  namespace: strimzi
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    topic.prefix: "defaultdb"
    name: "postgresql-defaultdb"
    database.hostname: "192.168.178.22"
    database.port: "5432"
    database.user: "rafi"
    database.dbname: "defaultdb"
    database.server.name: "defaultdb"
    connector.class: "io.debezium.connector.postgresql.PostgresConnector"
    tasks.max: "1"
    plugin.name: "pgoutput"
    slot.name: "defaultdb2"
    publication.name: "kafka_connect"
    table.include.list: "public.*"
    incremental.snapshot.chunk.size: "524288"
    heartbeat.interval.ms: "1000"
    key.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    errors.log.enable: "true"
    errors.log.include.messages: "true"
    decimal.handling.mode: "double"
    time.precision.mode: "connect"
