apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: kind-lab-vault
    namespace: vault
  project: default
  sources:
  
  - repoURL: https://helm.releases.hashicorp.com
    chart: vault
    helm:
      valueFiles: 
      - $values/root/vault/values.yaml
    targetRevision: 0.8.21
  - repoURL: https://github.com/rafimojabi/onetime-argo.git 
    targetRevision: HEAD
    ref: values
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: baseline
        pod-security.kubernetes.io/enforce-version: latest
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true